insert ignore into `vid_serie` (`id_serie`, `name`, `rate`, `description`, `duration`) values
(1, 'dolor', 2.51, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 19),
(2, 'lorem id ligula', 0.53, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 62),
(3, 'turpis enim', 0.76, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 35),
(4, 'neque sapien placerat', 4.19, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 24),
(5, 'at', 0.18, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 52),
(6, 'nisl duis ac nibh', 4.11, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 24),
(7, 'elementum ligula vehicula', 1.59, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 49),
(8, 'tempor convallis nulla', 3.44, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 56),
(9, 'elit proin risus praesent', 2.45, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 19),
(10, 'id mauris vulputate', 1.71, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 62),
(11, 'accumsan tortor', 2.6, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 37),
(12, 'blandit ultrices enim', 1.67, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 35),
(13, 'vulputate ut ultrices vel augue', 1.87, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 49),
(14, 'orci nullam molestie nibh', 1.48, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 26),
(15, 'ornare', 0.74, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 18),
(16, 'tincidunt nulla', 4.95, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 47),
(17, 'consectetuer adipiscing elit', 2.84, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 64),
(18, 'sit amet sapien dignissim', 1.59, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 17),
(19, 'sit amet', 0.42, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 25),
(20, 'potenti cras', 1.24, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 58),
(21, 'ut rhoncus aliquet pulvinar sed', 0.68, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 53),
(22, 'sapien non', 3.42, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 24),
(23, 'vulputate nonummy maecenas tincidunt lacus', 4.89, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 45),
(24, 'dui vel sem sed sagittis', 4.57, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 40),
(25, 'quis tortor id', 2.94, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 49),
(26, 'leo', 2.98, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 62),
(27, 'nunc vestibulum ante', 3.13, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 45),
(28, 'blandit lacinia erat', 4.03, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 26),
(29, 'mauris sit', 3.92, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 29),
(30, 'eu mi nulla ac enim', 2.04, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 51),
(31, 'in blandit', 3.07, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 54),
(32, 'risus praesent lectus', 4.73, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 53),
(33, 'fusce consequat nulla nisl', 2.65, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 38),
(34, 'orci', 1.6, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 65),
(35, 'dui vel', 0.06, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 46),
(36, 'in eleifend quam a odio', 2.64, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 19),
(37, 'eget orci vehicula', 1.05, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 45),
(38, 'congue', 3.54, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 50),
(39, 'mattis odio', 1.95, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 53),
(40, 'dui vel nisl duis', 0.22, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 49),
(41, 'pede justo', 0.84, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 22),
(42, 'fringilla rhoncus mauris', 2.71, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 45),
(43, 'sem fusce consequat nulla', 3.76, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 46),
(44, 'sociis natoque', 4.17, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 29),
(45, 'nisi eu', 3.88, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 44),
(46, 'posuere cubilia', 2.02, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 16),
(47, 'maecenas pulvinar lobortis', 2.66, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 34),
(48, 'nullam molestie nibh in', 4.87, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 57),
(49, 'diam vitae quam suspendisse', 0.21, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 20),
(50, 'habitasse platea dictumst aliquam', 4.65, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 61),
(51, 'posuere cubilia curae nulla', 0.81, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 30),
(52, 'mi sit amet lobortis', 0.11, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 52),
(53, 'nec', 2.02, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 57),
(54, 'pulvinar nulla pede ullamcorper augue', 4.61, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 63),
(55, 'sociis', 2.01, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 29),
(56, 'condimentum curabitur in', 2.68, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 43),
(57, 'dolor morbi vel lectus', 0.42, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 62),
(58, 'aenean', 0.58, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 15),
(59, 'interdum in ante vestibulum ante', 3.35, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 25),
(60, 'porta volutpat quam pede lobortis', 0.79, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 65),
(61, 'integer ac', 2.04, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 33),
(62, 'luctus et ultrices posuere', 1.6, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 56),
(63, 'at turpis donec posuere', 3.33, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 18),
(64, 'augue', 2.52, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 56),
(65, 'ligula', 1.31, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 63),
(66, 'donec pharetra magna', 4.61, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 30),
(67, 'dapibus at diam', 0.12, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 46),
(68, 'sed sagittis nam', 4.32, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 25),
(69, 'ut', 3.22, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 21),
(70, 'cum sociis natoque penatibus', 4.95, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 16),
(71, 'varius ut blandit non interdum', 1.12, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 51),
(72, 'sagittis nam congue risus semper', 2.8, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 44),
(73, 'primis in faucibus orci', 4.56, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 49),
(74, 'sapien ut nunc vestibulum', 2.94, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 51),
(75, 'id ornare imperdiet', 4.8, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 43),
(76, 'sem fusce', 2.05, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 45),
(77, 'tincidunt lacus at velit', 2.28, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 32),
(78, 'tristique in tempus sit', 3.17, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 61),
(79, 'mauris', 3.71, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 43),
(80, 'pede', 4.82, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 16),
(81, 'vulputate luctus cum sociis', 0.58, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 37),
(82, 'sodales scelerisque mauris', 3.34, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 22),
(83, 'primis in faucibus', 3.13, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 33),
(84, 'ligula', 1.18, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 36),
(85, 'sit amet diam', 3.29, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 16),
(86, 'leo pellentesque ultrices mattis', 2.43, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 58),
(87, 'id nulla ultrices aliquet', 2.13, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 25),
(88, 'aliquet maecenas leo odio condimentum', 3.46, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 39),
(89, 'congue vivamus metus arcu', 2.48, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 52),
(90, 'vestibulum vestibulum', 3.54, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 29),
(91, 'consectetuer adipiscing', 4.07, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 25),
(92, 'nunc viverra dapibus nulla', 4, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 21),
(93, 'et magnis dis parturient montes', 1.87, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 18),
(94, 'lacus curabitur', 4.07, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 60),
(95, 'ipsum', 0.35, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 31),
(96, 'luctus cum sociis natoque penatibus', 2.43, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 62),
(97, 'vehicula', 0.86, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 50),
(98, 'at turpis a', 2.92, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 48),
(99, 'risus', 2.62, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 24),
(100, 'tempus semper', 3.43, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 62);